/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as TreatmentsRouteImport } from './routes/treatments'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppointmentsAppointmentIdRouteImport } from './routes/appointments.$appointmentId'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsRoute = TreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsAppointmentIdRoute =
  AppointmentsAppointmentIdRouteImport.update({
    id: '/$appointmentId',
    path: '/$appointmentId',
    getParentRoute: () => AppointmentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/testimonials': typeof TestimonialsRoute
  '/treatments': typeof TreatmentsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/appointments/$appointmentId': typeof AppointmentsAppointmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/testimonials': typeof TestimonialsRoute
  '/treatments': typeof TreatmentsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/appointments/$appointmentId': typeof AppointmentsAppointmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/testimonials': typeof TestimonialsRoute
  '/treatments': typeof TreatmentsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/appointments/$appointmentId': typeof AppointmentsAppointmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/appointments'
    | '/book'
    | '/contact'
    | '/doctors'
    | '/gallery'
    | '/login'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/testimonials'
    | '/treatments'
    | '/update-password'
    | '/appointments/$appointmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appointments'
    | '/book'
    | '/contact'
    | '/doctors'
    | '/gallery'
    | '/login'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/testimonials'
    | '/treatments'
    | '/update-password'
    | '/appointments/$appointmentId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/appointments'
    | '/book'
    | '/contact'
    | '/doctors'
    | '/gallery'
    | '/login'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/testimonials'
    | '/treatments'
    | '/update-password'
    | '/appointments/$appointmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppointmentsRoute: typeof AppointmentsRouteWithChildren
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  DoctorsRoute: typeof DoctorsRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TreatmentsRoute: typeof TreatmentsRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments': {
      id: '/treatments'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof TreatmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/$appointmentId': {
      id: '/appointments/$appointmentId'
      path: '/$appointmentId'
      fullPath: '/appointments/$appointmentId'
      preLoaderRoute: typeof AppointmentsAppointmentIdRouteImport
      parentRoute: typeof AppointmentsRoute
    }
  }
}

interface AppointmentsRouteChildren {
  AppointmentsAppointmentIdRoute: typeof AppointmentsAppointmentIdRoute
}

const AppointmentsRouteChildren: AppointmentsRouteChildren = {
  AppointmentsAppointmentIdRoute: AppointmentsAppointmentIdRoute,
}

const AppointmentsRouteWithChildren = AppointmentsRoute._addFileChildren(
  AppointmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppointmentsRoute: AppointmentsRouteWithChildren,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  DoctorsRoute: DoctorsRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TestimonialsRoute: TestimonialsRoute,
  TreatmentsRoute: TreatmentsRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
